language: r
sudo: false
cache: false

r:
  - oldrel
  - release

os:
  - osx

script:
  - Rscript -e "rmarkdown::render('examples/lecture-16.Rmd')"
  - Rscript -e "rmarkdown::render('assignments/lab-15-replication/docs/lab-15-replication.Rmd')"
  